on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Earth-Quake Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Solution
        run: dotnet build
      - name: Test Solution
        run: dotnet test